# Generated by Django 3.2.7 on 2022-05-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_provider_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='logo_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
