# Generated by Django 3.2.7 on 2022-05-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_provider_logo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rate_average',
            field=models.FloatField(null=True),
        ),
    ]
