# Generated by Django 3.2.7 on 2022-05-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_cast_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_path',
            field=models.TextField(null=True),
        ),
    ]
