# Generated by Django 3.2.12 on 2022-05-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220520_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='partner_id',
            field=models.IntegerField(null=True),
        ),
    ]
