# Generated by Django 3.2.12 on 2022-05-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_partner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='partner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
