# Generated by Django 3.2.7 on 2022-05-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('poster_path', models.TextField()),
                ('original_title', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('tagline', models.TextField()),
                ('vote_average', models.FloatField()),
                ('overview', models.TextField()),
                ('release_date', models.TextField()),
                ('runtime', models.IntegerField()),
            ],
        ),
    ]
