# Generated by Django 3.2.7 on 2022-05-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_path', models.TextField()),
                ('adult', models.BooleanField()),
                ('overview', models.TextField()),
            ],
        ),
    ]
