# Generated by Django 3.2.7 on 2022-05-19 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_cast_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cast',
            old_name='charater',
            new_name='character',
        ),
    ]
